services:
  - type: web
    name: bank-interface-flow
    env: node
    region: frankfurt
    buildCommand: npm install --include=dev && npm run server:build && npm run expo:static:build && ls -R static-build
    startCommand: npm run server:prod
    healthCheckPath: /api/server-date
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: bank-db
          property: connectionString

databases:
  - name: bank-db
    databaseName: bank
    user: bank_user
    region: frankfurt
    plan: free
